# Generated by Django 6.0.4 on 2026-04-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_fr', models.CharField(max_length=200)),
                ('texte_moore', models.CharField(blank=True, max_length=200)),
                ('texte_dioula', models.CharField(blank=True, max_length=200)),
                ('texte_fulfude', models.CharField(blank=True, max_length=200)),
                ('poids', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='contenus.question')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponse',
                'ordering': ['ordre'],
            },
        ),
    ]
