# Generated by Django 6.0.4 on 2026-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=300)),
                ('ville', models.CharField(default='Ouagadougou', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('horaires', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('audio_fr', models.FileField(blank=True, null=True, upload_to='audio/centres/fr/')),
                ('audio_moore', models.FileField(blank=True, null=True, upload_to='audio/centres/moore/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre de santé',
                'verbose_name_plural': 'Centres de santé',
                'ordering': ['ville', 'distance_km'],
            },
        ),
    ]
