# Generated by Django 6.0.4 on 2026-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatAnonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=7, unique=True)),
                ('nb_evaluations', models.IntegerField(default=0)),
                ('nb_faible', models.IntegerField(default=0)),
                ('nb_modere', models.IntegerField(default=0)),
                ('nb_eleve', models.IntegerField(default=0)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistique anonyme',
                'verbose_name_plural': 'Statistiques anonymes',
                'ordering': ['-periode'],
            },
        ),
    ]
