# Generated by Django 6.0.4 on 2026-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuEducatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('cancer', 'Cancer du sein'), ('signes', 'Signes précoces'), ('prevention', 'Prévention'), ('risques', 'Facteurs de risque')], max_length=20)),
                ('ordre', models.IntegerField()),
                ('titre_fr', models.CharField(max_length=200)),
                ('titre_moore', models.CharField(blank=True, max_length=200)),
                ('titre_dioula', models.CharField(blank=True, max_length=200)),
                ('titre_fulfude', models.CharField(blank=True, max_length=200)),
                ('texte_fr', models.TextField()),
                ('texte_moore', models.TextField(blank=True)),
                ('texte_dioula', models.TextField(blank=True)),
                ('texte_fulfude', models.TextField(blank=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('audio_fr', models.FileField(blank=True, null=True, upload_to='audio/fr/')),
                ('audio_moore', models.FileField(blank=True, null=True, upload_to='audio/moore/')),
                ('audio_dioula', models.FileField(blank=True, null=True, upload_to='audio/dioula/')),
                ('audio_fulfude', models.FileField(blank=True, null=True, upload_to='audio/fulfude/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu éducatif',
                'verbose_name_plural': 'Contenus éducatifs',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='EtapeAutoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etape', models.IntegerField(unique=True)),
                ('titre_fr', models.CharField(max_length=200)),
                ('titre_moore', models.CharField(blank=True, max_length=200)),
                ('titre_dioula', models.CharField(blank=True, max_length=200)),
                ('titre_fulfude', models.CharField(blank=True, max_length=200)),
                ('description_fr', models.TextField()),
                ('description_moore', models.TextField(blank=True)),
                ('description_dioula', models.TextField(blank=True)),
                ('description_fulfude', models.TextField(blank=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='etapes/')),
                ('audio_fr', models.FileField(blank=True, null=True, upload_to='audio/etapes/fr/')),
                ('audio_moore', models.FileField(blank=True, null=True, upload_to='audio/etapes/moore/')),
                ('audio_dioula', models.FileField(blank=True, null=True, upload_to='audio/etapes/dioula/')),
                ('audio_fulfude', models.FileField(blank=True, null=True, upload_to='audio/etapes/fulfude/')),
            ],
            options={
                'verbose_name': 'Étape auto-examen',
                'verbose_name_plural': 'Étapes auto-examen',
                'ordering': ['numero_etape'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(unique=True)),
                ('type_reponse', models.CharField(choices=[('oui_non', 'Oui / Non'), ('choix_multiple', 'Choix multiple')], default='choix_multiple', max_length=20)),
                ('poids_max', models.IntegerField(default=3)),
                ('enonce_fr', models.TextField()),
                ('enonce_moore', models.TextField(blank=True)),
                ('enonce_dioula', models.TextField(blank=True)),
                ('enonce_fulfude', models.TextField(blank=True)),
                ('audio_fr', models.FileField(blank=True, null=True, upload_to='audio/questions/fr/')),
                ('audio_moore', models.FileField(blank=True, null=True, upload_to='audio/questions/moore/')),
                ('audio_dioula', models.FileField(blank=True, null=True, upload_to='audio/questions/dioula/')),
                ('audio_fulfude', models.FileField(blank=True, null=True, upload_to='audio/questions/fulfude/')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
    ]
